app/dashboard/forms.py
"""All of the forms required for dashboard functionality
"""

from flask_wtf import FlaskForm
from wtforms import (
    SubmitField,
    DecimalField,
    IntegerField,
    SelectField,
    RadioField,
    SelectMultipleField,
)
from wtforms.widgets import CheckboxInput, ListWidget
from wtforms.validators import DataRequired, NumberRange


class MedicationForm(FlaskForm):
    """Form for adding medications to the users profile/dashboard."""

    # Medication dosage field
    dosage = DecimalField(
        "Dosage", validators=[DataRequired(), NumberRange(min=0, max=120)]
    )
    # Users can select different measurements of medication
    unit = SelectField(
        "Unit",
        choices=[
            ("mg", "mg"),
            ("mL", "mL"),
            ("g", "g"),
            ("L", "L"),
            ("units", "Units"),
        ],
        validators=[DataRequired()],
        default="mg",
    )
    # The time at which a user takes their medication
    time_of_day = RadioField(
        "Time of Day",
        choices=[
            ("morning", "Morning"),
            ("afternoon", "Afternoon"),
            ("evening", "Evening"),
            ("night", "Night"),
            ("as_needed", "As Needed"),
        ],
        default="as_needed",
        validators=[DataRequired()],
    )
    # The days when a user takes their medications
    days_of_week = SelectMultipleField(
        "Days of the Week",
        choices=[
            ("monday", "Monday"),
            ("tuesday", "Tuesday"),
            ("wednesday", "Wednesday"),
            ("thursday", "Thursday"),
            ("friday", "Friday"),
            ("saturday", "Saturday"),
            ("sunday", "Sunday"),
        ],
        widget=ListWidget(prefix_label=False),
        option_widget=CheckboxInput(),
    )
    # Medication price
    price = DecimalField(
        "Price", validators=[DataRequired(), NumberRange(min=1, max=100000)]
    )
    # How long a user takes this medication
    duration = IntegerField(
        "Duration (Days)", validators=[DataRequired(), NumberRange(min=1, max=30)]
    )
    # Submit button
    submit = SubmitField("Add Medication")

app/dashboard/__init__.py
"""Blueprint for dashboard
"""

from flask import Blueprint

dash = Blueprint("dash", __name__)

from app.dashboard import routes

app/dashboard/routes.py
"""
Routes for managing the dashboard of the application.

This module contains various Flask routes that provide functionality for
logged-in users to manage their medications. It includes features for
viewing, adding, updating, and deleting medications, as well as searching
for medications and managing user settings.

Key Functions:
- dashboard: Renders the user's dashboard with a summary of their medications.
- search_medication: Searches for medications based on the user's query.
- add_medication: Allows users to add a new medication or edit an existing one.
- update_medication_status: Toggles the status of a medication between 'taken' 
    and 'not taken'.
- delete_medication: Deletes a specified medication for the logged-in user.
- schedule: Renders the schedule page.
- forum: Renders the forum page.
- settings: Handles user settings management, including updating profile
    information and changing passwords.
- change_password: Processes password change requests.

Each route is protected by the `login_required` decorator, ensuring that
only authenticated users can access these functionalities.

Module Dependencies:
- Flask: Web framework for building the application.
- Flask-Login: Extension for managing user sessions.
- SQLAlchemy: ORM for interacting with the database.
- datetime: Standard library for date and time manipulation.
"""

from datetime import datetime, timedelta, date
from flask import flash, redirect, render_template, request, url_for, jsonify
from flask_login import (
    current_user,
    login_required,
)

from app.dashboard import dash
from app.extensions import db
from app.models.medication import Medications
from app.models.medicationData import MedicationData
from app.dashboard.forms import MedicationForm


@dash.route("/dashboard", methods=["GET", "POST"])
@login_required
def dashboard():
    """
    Render the user's dashboard with a summary of their medications.

    This function retrieves all medications associated with the currently
    logged-in user, organizes them by day of the week and time of day, and
    renders the dashboard template.

    Returns:
        Rendered template for the dashboard with grouped medications and the
        current day.
    """
    # Current signed in users id
    user_id = current_user.id

    grouped_meds = get_grouped_meds(user_id=user_id)

    today = datetime.now().strftime("%A")

    current_date = datetime.now().strftime("%B %d, %Y")

    return render_template(
        "dashboard/dashboard.html",
        current_user=current_user,
        grouped_meds=grouped_meds,
        today=today,
        current_date=current_date,
    )


def reset():
    """Reset medication status to 'not taken' only for days not marked as 'taken'."""
    today = datetime.today().date()
    today_str = today.strftime("%Y-%m-%d")  # Format today's date as a string
    medications = Medications.query.all()

    for medication in medications:
        days_taken = medication.days_taken.split(",") if medication.days_taken else []

        # If today's date is not in `days_taken`, reset the status to 'not taken'
        if today_str not in days_taken:
            medication.status = "not taken"
        else:
            # If today is already marked as 'taken', keep the status as 'taken'
            medication.status = "taken"

        db.session.commit()


def get_grouped_meds(user_id):
    """Helper function to group medications by day of the week and time of day."""
    medications = (
        db.session.query(Medications, MedicationData)
        .join(MedicationData)
        .filter(Medications.user_id == user_id)
        .all()
    )

    # Group medications by day of the week and time of day
    days = [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
    ]

    grouped_meds = {
        day: {
            "Morning": [],
            "Afternoon": [],
            "Evening": [],
            "Night": [],
            "As Needed": [],
        }
        for day in days
    }

    for med, med_data in medications:
        days_of_week = med.days_of_week.split(",")
        for day in days_of_week:
            day_capitalized = day.strip().capitalize()

            if day_capitalized == "All":
                for day_key in grouped_meds.keys():
                    time_of_day_capitalized = (
                        med.time_of_day.capitalize() if med.time_of_day else "As Needed"
                    )
                    if time_of_day_capitalized not in grouped_meds[day_key]:
                        grouped_meds[day_key][time_of_day_capitalized] = []
                    grouped_meds[day_key][time_of_day_capitalized].append(
                        (med, med_data)
                    )
            else:
                time_of_day_capitalized = (
                    med.time_of_day.capitalize() if med.time_of_day else "As Needed"
                )
                if day_capitalized in grouped_meds:
                    if time_of_day_capitalized not in grouped_meds[day_capitalized]:
                        grouped_meds[day_capitalized][time_of_day_capitalized] = []
                    grouped_meds[day_capitalized][time_of_day_capitalized].append(
                        (med, med_data)
                    )

    return grouped_meds


@dash.route("/search_medication", methods=["GET"])
@login_required
def search_medication():
    """
    Search for medications based on the user's query.
    """
    query = request.args.get("query", "").strip()

    # Return nothing if the query is empty
    if not query:
        return "", 204  # Empty response with 204 (No Content) status

    # Perform the search query
    search_results = MedicationData.query.filter(
        MedicationData.drug_name.ilike(f"%{query}%")
    ).all()

    # Render the search results
    return render_template("dashboard/search_results.html", medications=search_results)


def get_next_day_of_week(created_at, target_days):
    """Calculate the nearest future date for one of the target days of the week."""
    day_name_to_index = {
        "Monday": 0,
        "Tuesday": 1,
        "Wednesday": 2,
        "Thursday": 3,
        "Friday": 4,
        "Saturday": 5,
        "Sunday": 6,
    }
    target_day_indexes = [day_name_to_index[day] for day in target_days]

    for i in range(7):
        next_date = created_at + timedelta(days=i)
        if next_date.weekday() in target_day_indexes:
            return next_date
    return created_at  # Default to created_at if no match is found


@dash.route("/add_medication", methods=["GET", "POST"])
@dash.route("/add_medication/<int:id>", methods=["GET", "POST"])
@login_required
def add_medication(id=None):
    """
    Add a new medication for the logged-in user.

    This function handles the addition of a medication either through a POST
    request with a submitted form or by pre-filling the form with existing
    medication data if an ID is provided in the URL. The medication is
    associated with the currently logged-in user.

    If the form is submitted and valid, the medication details are extracted,
    and the medication is added to the database. The function then redirects
    the user to the dashboard. If no medication is found with the provided
    ID, an error message is printed to the console.

    Parameters:
        id (int): The ID of the medication to edit (optional). If not provided,
        a new medication will be added.

    Returns:
        Rendered template for the add medication form or redirects to the
        dashboard after successful submission.
    """
    form = MedicationForm()
    if form.validate_on_submit():
        dosage = form.dosage.data
        unit = form.unit.data
        price = form.price.data
        duration = form.duration.data
        time_of_day = form.time_of_day.data
        days_of_week = form.days_of_week.data

        if len(days_of_week) == 7:
            days_of_week_str = "all"
        else:
            days_of_week_str = ", ".join(days_of_week) if days_of_week else "all"

        created_at = date.today()  # Use today's date as the creation date

        # Calculate the start date based on the selected days
        if days_of_week_str != "all":
            # Split and calculate the closest start date based on created_at and selected days
            target_days = [day.strip().capitalize() for day in days_of_week]
            start_listing_date = get_next_day_of_week(created_at, target_days)
        else:
            # If "all" days are selected, start from created_at
            start_listing_date = created_at

        if id is not None:
            medication = (
                db.session.query(MedicationData).filter(MedicationData.id == id).first()
            )
            if medication:
                new_medication = Medications(
                    user_id=current_user.id,
                    name=medication.drug_name,
                    description=medication.medical_condition_description,
                    dosage=f"{dosage} {unit}".strip(),
                    price=price,
                    duration=duration,
                    medication_data=id,
                    time_of_day=time_of_day,
                    days_of_week=days_of_week_str,
                    created_at=created_at,  # Record the creation date
                )

                db.session.add(new_medication)
                db.session.commit()

                print(f"Medication added: {new_medication}")
                return redirect(url_for("dash.dashboard"))
            else:
                print("No medication found with the given ID.")

    return render_template("dashboard/add_medications.html", form=form)


@dash.route("/medication/update_status/<int:med_id>", methods=["POST"])
@login_required
def update_medication_status(med_id):
    """
    Update the status of a medication for the logged-in user.

app/templates/dashboard/add_medications.html
{% extends "base.html" %}
{% block title %}Schedule{% endblock %}
{% block content %}
<div class="container">
  <h1 class="text-center">Add Medications</h1>
  <p class="text-center">This is the schedule page content.</p>
  <form method="POST" action="" class="card-body p-3 rounded text-muted p-3">
    {{ form.hidden_tag() }}
    <div class="card-body rounded p-3 text-bg-dark">
      <div class="form-group p-2">
        <div class="mb-3 row">
          <div class="col">
            {{ form.dosage.label(class="form-label") }}
            {{ form.dosage(class="form-control", placeholder="Dosage") }}
          </div>
          <div class="col-sm-5">
            {{ form.unit.label(class="form-label") }}
            {{ form.unit(class="form-select") }}
          </div>
        </div>
      </div>
      <div class="form-group mb-3 p-2">
        <label class="form-label h4">Time of Day</label>
        <div class="form-check form-check">
          {% for subfield in form.time_of_day %}
          <div class="form-check form-check-inline p-2">
            {{ subfield(class="form-check-input", id="option5") }} <!-- Radio input -->
            {{ subfield.label(class="form-check-label") }} <!-- Radio label -->
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="form-group p-2">
        {{ form.days_of_week.label(class="form-label h4 mb-3") }}
        <div class="form-check">
          <input type="checkbox" id="selectAll" class="form-check-input" />
          <label for="selectAll" class="form-check-label">Select All</label>
        </div>
        <div class="form-check form-check-inline">
          {% for subfield in form.days_of_week %}
          <div class="form-check form-check-inline p-2">
            {{ subfield(class="form-check-input") }} <!-- Checkbox input -->
            {{ subfield.label(class="form-check-label") }} <!-- Checkbox label -->
          </div>
          {% endfor %}
        </div>
      </div>

      <div class="form-group mb-3">
        {{ form.price.label(class="form-label") }}
        {{ form.price(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.duration.label(class="form-label") }}
        {{ form.duration(class="form-control") }}
      </div>
      <div class="form-group p-2">
        {{ form.submit(class="btn mt-3", style="background-color: #F18F01") }}
        <a href="{{ url_for('dash.dashboard') }}" class="btn btn-light mt-3">Back to Dashboard</a>
      </div>
    </div>
  </form>
  <script>
    document.getElementById('selectAll').onclick = function () {
      const checkboxes = document.querySelectorAll('input[type="checkbox"][name="days_of_week"]');
      checkboxes.forEach((checkbox) => {
        checkbox.checked = this.checked;
      });
    };
  </script>
</div>
{% endblock %}

app/templates/dashboard/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->

        <!-- Sidebar -->
        <!-- Main content -->
        <main class="col mr-3">
            <div class="container pt-4">
                <!-- Header with User and Date -->
                <h2>Welcome {{ current_user.username }}</h2>
                <p>{{ current_date }}</p>
            </div>
            <!-- Search Bar -->
            <div class="container">
                <div class="row justify-content-center">
                    <!-- Search bar -->
                    <div class="col-12 col-md-12">
                        <form>
                            <div class="input-group">
                                <input type="text" name="query" class="form-control" placeholder="Search medication"
                                    aria-label="Search medication" hx-get="{{ url_for('dash.search_medication') }}"
                                    hx-target="#results" hx-trigger="keyup changed delay:50ms">
                            </div>
                        </form>
                        <!-- Search results -->
                        <ul id="results" class="list-group mt-2"></ul>
                    </div>
                </div>
            </div>

            <!-- Search Bar -->
            <!-- Where medications are listed -->
            <div class="container overflow-auto p-3 rounded" style="max-height: 40rem;">
                {% for day, times in grouped_meds.items() %}
                {% if times %}
                <h2 class="mt-4">{{ day }}</h2>
                <hr>
                <div class="row">
                    {% for time_of_day, meds in times.items() %}
                    {% if meds %}
                    <div class="col-md-12">
                        <h4 class="mt-4">{{ time_of_day.replace('_', ' ') }}</h4>
                        {% for med, med_data in meds %}
                        <div class="col-xl-12 col-md-12 ">
                            <div
                                class="card overflow-hidden mb-3 {% if day == today and med.status == 'taken' %}text-bg-success{% endif %}">
                                <div class="card-content">
                                    <div class="card-body d-flex justify-content-between align-items-center">
                                        <div class="d-flex align-items-center">
                                            <div>
                                                <h4 class="mb-0">{{ med.name | title }} <i
                                                        class="fas fa-info-circle info-icon" data-bs-toggle="modal"
                                                        data-bs-target="#infoModal{{ med.id }}"></i> </h4>
                                                <span>{{ med.dosage }} - ${{ "%.2f"|format(med.price) }}</span>
                                            </div>
                                        </div>

                                        {% if day == today %}
                                        <form action="{{ url_for('dash.update_medication_status', med_id=med.id) }}"
                                            method="POST" style="display: inline;">
                                            {% if med.status == 'taken' %}
                                            <button type="submit" class="btn btn-light">Mark
                                                as Not Taken</button>
                                            {% else %}
                                            <button type="submit" class="btn btn-primary">Mark
                                                as Taken</button>
                                            {% endif %}
                                        </form>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Modal -->
                        <div class="modal fade" id="infoModal{{ med.id }}" tabindex="-1"
                            aria-labelledby="infoModalLabel{{ med.id }}" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="infoModalLabel{{ med.id }}">{{ med.name }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <!-- Medication Data -->
                                        <p><strong>Prescription Status:</strong> {{ med_data.rx_otc }}</p>
                                        <p><strong>Dosage:</strong> {{ med.dosage }}</p>
                                        <p><strong>Price:</strong> ${{ "%.2f"|format(med.price) }}</p>
                                        <p><strong>Duration:</strong> {{ med.duration }} days</p>
                                        <p><strong>Pregnancy Category:</strong>
                                            {% set pregnancy_categories = {
                                            'A': 'Controlled studies show no risk.',
                                            'B': 'No evidence of risk in humans.',
                                            'C': 'Risk cannot be ruled out.',
                                            'D': 'Positive evidence of risk.',
                                            'X': 'Contraindicated in pregnancy'
                                            } %}
                                            {{ med_data.pregnancy_category }}
                                            <span style="color: gray;">({{
                                                pregnancy_categories.get(med_data.pregnancy_category, 'Unknown
                                                category') }})</span>
                                        </p>
                                        <p><strong>Interactions With Alcohol:</strong>
                                            {% if med_data.alcohol == 'X' %}
                                            Yes
                                            {% else %}
                                            No
                                            {% endif %}
                                        </p>
                                        <p><strong>Schedule:</strong> {{ med_data.csa }}</p>
                                        <p><strong>Condition Description:</strong> {{ med.description }}</p>
                                        <p><strong>More Information:</strong> <a href="{{ med_data.drug_link }}"
                                                target="_blank">{{ med_data.drug_link }}</a></p>
                                        <!-- Medication Data -->
                                        <!-- Delete Button -->
                                        <form method="POST"
                                            action="{{ url_for('dash.delete_medication', med_id=med.id) }}">
                                            <button type="submit" class="btn btn-danger"
                                                onclick="return confirm('Are you sure you want to delete this medication?');">Delete
                                                {{ med.name }}</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Modal -->
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <!-- Where medications are listed -->
        </main>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const searchInput = document.querySelector('input[name="query"]');
        const resultsContainer = document.querySelector("#results");

        searchInput.addEventListener("input", function () {
            const query = searchInput.value.trim();

            if (query === "") {
                // Clear and hide the results container when input is empty
                resultsContainer.innerHTML = "";
                resultsContainer.style.display = "none";
                return; // Stop further processing
            } else {
                // Show the results container when typing
                resultsContainer.style.display = "block";
            }
        });
    });
</script>



<!--Main layout-->
{% endblock %}

app/templates/dashboard/schedule.html
{% extends "base.html" %}
{% block title %}Schedule{% endblock %}
{% block content %}
<div class="container-fluid align-items-center">
    <div class="row">
        <!-- Sidebar -->
        <!-- Sidebar -->
        <main class="col align-items-center bg-white" style="margin-top: 58px;">
            <h1>Schedule Page</h1>
            <div id="calendar">

            </div>
        </main>

    </div>
</div>
<script src="{{ url_for('static', filename='js/schedule.js') }}"></script>
{% endblock %}

app/templates/dashboard/search_results.html
{% for med in medications %}
<li class="list-group-item justify-content-center">
    <a href="{{ url_for('dash.add_medication', id=med.id) }}"><strong>{{ med.drug_name }}</strong></a><br>
    {{ med.medical_condition }}<br>
</li>
{% else %}
<li class="list-group-item">No results found.</li>
{% endfor %}

app/templates/dashboard/settings.html
{% extends "base.html" %}

{% block title %}{{ current_user.name }} Settings{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <!-- Main content -->
        <main class="col-md-8" style="margin-top: 58px;">
            <!-- Personal Information Section -->
            <div class="row align-items-center">
                <!-- TODO: FIX PROFILE IMAGE UPLOAD AND DISPLAY -->
                <!-- Profile Image -->
                <!-- <div class="col-md-4 text-center">
                    <div class="profile-img">
                        <img src="{{ url_for('static', filename='images/profile_placeholder.png') }}"
                            class="rounded-circle img-fluid" alt="Profile Image">
                        <input type="file" id="profileImageUpload" class="form-control mt-2"
                            aria-label="Upload Profile Image">
                        <label for="profileImageUpload" class="btn btn-light btn-sm mt-2">Click to change
                            photo</label>
                    </div>
                </div> -->
                <!-- Profile Image -->
                <!-- Account Details -->
                <div class="col-12">
                    <h4>Account Details</h4>
                    <form method="POST" action="{{ url_for('dash.settings') }}">
                        <!-- First Name -->
                        <div class="form-group mb-3">
                            <label for="firstName" class="form-label">First Name</label>
                            <input type="text" id="firstName" name="first_name" class="form-control"
                                value="{{ current_user.first_name }}">
                        </div>
                        <!-- First Name -->
                        <!-- Last Name -->
                        <div class="form-group mb-3">
                            <label for="lastName" class="form-label">Last Name</label>
                            <input type="text" id="lastName" name="last_name" class="form-control"
                                value="{{ current_user.last_name }}">
                        </div>
                        <!-- Last Name -->
                        <!-- Email -->
                        <div class="form-group mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" id="email" name="email" class="form-control"
                                value="{{ current_user.email }}">
                        </div>
                        <!-- Email -->
                        <!-- Submit Button -->
                        <button type="submit" class="btn btn-primary mt-4 w-100">Save New Changes</button>
                        <!-- Submit Button -->
                    </form>
                </div>
            </div>
            <!-- Personal Information Section -->

            <!-- Security Section -->
            <div class="row mt-5">
                <div class="col-12">
                    <h4>Security</h4>
                    <form method="POST" action="{{ url_for('dash.change_password') }}">
                        <!-- Current Password  -->
                        <div class="form-group mb-3">
                            <label for="currentPassword" class="form-label">Current Password</label>
                            <input type="password" id="currentPassword" name="current_password" class="form-control"
                                placeholder="Enter current password" required>
                        </div>
                        <!-- Current Password  -->
                        <!-- New Password  -->
                        <div class="form-group mb-3">
                            <label for="newPassword" class="form-label">New Password</label>
                            <input type="password" id="newPassword" name="new_password" class="form-control"
                                placeholder="Enter new password" required>
                        </div>
                        <!-- New Password  -->
                        <!-- Confirm New Password  -->
                        <div class="form-group mb-3">
                            <label for="confirmNewPassword" class="form-label">Confirm New Password</label>
                            <input type="password" id="confirmNewPassword" name="confirm_new_password"
                                class="form-control" placeholder="Confirm new password" required>
                        </div>
                        <!-- Confirm New Password  -->
                        <!-- Submit Button -->
                        <button type="submit" class="btn btn-outline-secondary w-100">Change Password</button>
                        <!-- Submit Button -->
                    </form>
                </div>
            </div>
            <!-- Security Section -->
        </main>
        <!-- Main Section -->
    </div>
</div>


{% endblock %}

app/templates/dashboard/sidebar.html
<!-- Sidebar -->
<nav id="sidebarMenu" class="d-lg-block col-lg-3 col-md-4 bg-white">
  <div class="d-flex flex-column h-100">
    <div class="position-sticky">
      <div class="list-group list-group-flush mx-3 mt-4">
        <a href="{{ url_for('dash.dashboard') }}" class="list-group-item list-group-item-action py-2 ripple"
          aria-current="true">
          <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Dashboard</span>
        </a>
        <a href="{{ url_for('dash.schedule') }}" class="list-group-item list-group-item-action py-2 ripple">
          <i class="fas fa-chart-area fa-fw me-3"></i><span>Schedule</span>
        </a>
        <!-- <a href="{{ url_for('dash.forum') }}" class="list-group-item list-group-item-action py-2 ripple">
          <i class="fas fa-lock fa-fw me-3"></i><span>Forum</span>
        </a> -->
        <a href="{{ url_for('dash.settings') }}" class="list-group-item list-group-item-action py-2 ripple">
          <i class="fas fa-cog fa-fw me-3"></i><span>Settings</span>
        </a>
      </div>
    </div>
    <!-- Spacer -->
    <!-- <div class="mt-auto">
      <a href="{{ url_for('dash.settings') }}" class="list-group-item list-group-item-action py-2 ripple">
        <i class="fas fa-cog fa-fw me-3"></i><span>Settings</span>
      </a>
      <a href="{{ url_for('auth.logout') }}" class="list-group-item list-group-item-action py-2 ripple">
        <i class="fas fa-sign-out-alt fa-fw me-3"></i><span>Logout</span>
      </a>
    </div> -->
  </div>
</nav>
<!-- Sidebar -->